[RQ-802] feat: integration of session replay with test this rule
requestly/requestly pull request #1051
Opened 2023-09-14 13:15 UTC by nafees87n

Closes issue:  RQ-802

## 📜 Summary of changes:

## ✅ Checklist:

- [ ] Make sure linting and unit tests pass.
- [ ] No install/build warnings introduced.
- [ ] Verified UI in browser.
- [ ] For UI changes, added/updated analytics events (if applicable).
- [ ] For changes in extension's code, manually tested in Chrome and Firefox.
- [ ] For changes in extension's code, both MV2 and MV3 are covered.
- [ ] Added/updated unit tests for this change.
- [ ] Raised pull request to update corresponding documentation (if already exists).

## 🧪 Test instructions:

## 🔗 Other references:

2023-09-18 11:16 UTC, rohanmathur91 requested changes
UI is broken for large URLs
<img width="803" alt="Screenshot 2023-09-18 at 4 27 59 PM" src="https://github.com/requestly/requestly/assets/61556757/7b44a0de-e6d7-41e2-82f8-36dcef0ec3e9">

2023-09-18 11:50 UTC, rohanmathur91 commented on app/src/components/features/rules/TestThisRule/index.css
> +  width: 90vw !important;
you can pass `Width` prop directly to the <RQModal> component

2023-09-18 12:26 UTC, rohanmathur91 approved these changes

2023-09-18 17:40 UTC, wrongsahil approved these changes

2023-09-18 17:42 UTC, wrongsahil requested changes
We will need to add compatibilityFlag for starting recording with session enabled

2023-09-18 18:26 UTC, wrongsahil requested changes

2023-09-18 18:26 UTC, wrongsahil commented on app/src/components/features/rules/TestThisRule/index.tsx
> +  const [recordTestPage, setRecordTestPage] = useState<boolean>(!!isFeatureCompatible(FEATURES.TEST_THIS_RULE_SESSION));
This is uneccessary as event if we send record=true to older extension, it wont still record the page.

2023-09-19 07:41 UTC, wrongsahil approved these changes

2023-09-19 07:46 UTC, merged