[RQ-893] session replay on appSumo
requestly/requestly pull request #1072
Opened 2023-09-21 14:58 UTC by nafees87n

Closes issue: 

## 📜 Summary of changes:

## ✅ Checklist:

- [ ] Make sure linting and unit tests pass.
- [ ] No install/build warnings introduced.
- [ ] Verified UI in browser.
- [ ] For UI changes, added/updated analytics events (if applicable).
- [ ] For changes in extension's code, manually tested in Chrome and Firefox.
- [ ] For changes in extension's code, both MV2 and MV3 are covered.
- [ ] Added/updated unit tests for this change.
- [ ] Raised pull request to update corresponding documentation (if already exists).

## 🧪 Test instructions:

## 🔗 Other references:

2023-09-22 06:53 UTC, RuntimeTerror10 commented on app/src/components/user/AccountIndexPage/ManageAccount/ManageTeams/TeamViewer/BillingDetails/index.js
> +            {`This workspace has an active Session Replay Lifetime Pro subscription for ${appSumoSubscriptionInfo?.codes?.length} members.`}
Can we handle `members` substring for single and multiple members?
keep it `members` for more than 1 else `member`

2023-09-22 06:53 UTC, RuntimeTerror10 commented on app/src/components/user/AccountIndexPage/ManageAccount/ActiveLicenseInfo/index.js
> +  const [sessionReplatLifeTimeDetails, setSessionReplatLifeTimeDetails] = useState({});
typo `sessionReplayLifeTimeDetails`

2023-09-22 06:53 UTC, RuntimeTerror10 commented on app/src/components/landing/Appsumo/Appsumo.tsx
> +  }, 800);
wrap this in useMemo

2023-09-22 06:58 UTC, RuntimeTerror10 commented on app/src/hooks/DbListenerInit/availableTeamsListener.js
> +
This attribute will be set every time there is a change, is this intentional?

2023-09-22 07:35 UTC, RuntimeTerror10 approved these changes

2023-09-26 07:21 UTC, wrongsahil requested changes

2023-09-26 07:21 UTC, wrongsahil commented on app/src/components/user/AccountIndexPage/ManageAccount/ActiveLicenseInfo/index.js
> +              validFrom: new Date(sessionReplayLifeTimeDetails.date).getTime(),
This will break for deals claimed from producthunt. Backward compatibility missing as this is in `epoch` not in dict in case of PH deal

2023-09-26 07:21 UTC, wrongsahil commented on app/src/components/landing/Appsumo/Appsumo.tsx
> +        const docRef = doc(db, "appSumoCodes", enteredCode);
This is not the correct way

2023-09-26 19:45 UTC, wrongsahil approved these changes

2023-09-27 07:26 UTC, merged