[RQ-869]: Search in session replay network table
requestly/requestly pull request #1084
Opened 2023-09-25 11:23 UTC by RuntimeTerror10

Closes issue: 

## 📜 Summary of changes:

## ✅ Checklist:

- [ ] Make sure linting and unit tests pass.
- [ ] No install/build warnings introduced.
- [ ] Verified UI in browser.
- [ ] For UI changes, added/updated analytics events (if applicable).
- [ ] For changes in extension's code, manually tested in Chrome and Firefox.
- [ ] For changes in extension's code, both MV2 and MV3 are covered.
- [ ] Added/updated unit tests for this change.
- [ ] Raised pull request to update corresponding documentation (if already exists).

## 🧪 Test instructions:

## 🔗 Other references:

2023-09-25 11:52 UTC, wrongsahil approved these changes

2023-09-25 12:13 UTC, rohanmathur91 commented on app/src/lib/design-system/components/RQNetworkTable/GenericNetworkTable/components/FiltersToolbar/FiltersToolbar.tsx
> +        onChange={(e) => onSearchFilterChange(e.target.value)}
This will update on every key stroke, we should add a debouce.

2023-09-25 12:24 UTC, rohanmathur91 commented on app/src/lib/design-system/components/RQNetworkTable/GenericNetworkTable/index.tsx
> +  const [filters, setFilters] = useState<Filters>({});
Define a initial search state
```tsx
  const [filters, setFilters] = useState<Filters>({search:""});
```

2023-09-25 12:25 UTC, rohanmathur91 commented on app/src/lib/design-system/components/RQNetworkTable/GenericNetworkTable/index.tsx
> +  };
Note: `includes` will match the empty string

```suggestion
  const filterLog = useCallback((networkLog: NetworkLog) => {
    const entry = networkEntrySelector(networkLog);
    return !!entry?.request?.url?.includes(filters.search))
  },[])
```

2023-09-25 12:28 UTC, rohanmathur91 commented
Network Table looks weird when no logs matched
<img width="1293" alt="Screenshot 2023-09-25 at 5 35 16 PM" src="https://github.com/requestly/requestly/assets/61556757/224cfbc0-e45b-4d11-b3cd-969606db9a6b">

2023-09-25 12:37 UTC, rohanmathur91 requested changes

2023-09-25 12:37 UTC, rohanmathur91 commented on app/src/lib/design-system/components/RQNetworkTable/GenericNetworkTable/components/FiltersToolbar/FiltersToolbar.tsx
> +        onChange={(e) => onSearchFilterChange(e.target.value)}
This will update on every key stroke, we should add a debounce.

2023-09-25 12:37 UTC, rohanmathur91 commented on app/src/lib/design-system/components/RQNetworkTable/GenericNetworkTable/index.tsx
> +  const [filters, setFilters] = useState<Filters>({});
Define a initial search state
```tsx
  const [filters, setFilters] = useState<Filters>({search:""});
```

2023-09-25 12:37 UTC, rohanmathur91 commented on app/src/lib/design-system/components/RQNetworkTable/GenericNetworkTable/index.tsx
> +  };
Note: `includes` will match the empty string

```suggestion
  const filterLog = useCallback((networkLog: NetworkLog) => {
    const entry = networkEntrySelector(networkLog);
    return !!entry?.request?.url?.includes(filters.search))
  },[networkEntrySelector])
```

2023-09-26 05:32 UTC, rohanmathur91 commented on app/src/lib/design-system/components/RQNetworkTable/GenericNetworkTable/components/FiltersToolbar/FiltersToolbar.tsx
> +}
Put this interface in a separate `types.ts` file

2023-09-26 05:35 UTC, rohanmathur91 commented on app/src/lib/design-system/components/RQNetworkTable/GenericNetworkTable/index.tsx
> +      includeLog = !!entry?.request?.url?.includes(filters.search.toLowerCase()); // TODO: add checks for other filters here
Lowercase the URL too.

2023-09-26 05:35 UTC, rohanmathur91 approved these changes

2023-09-26 05:55 UTC, merged