feat(mock-server): improve headers UI
requestly/requestly pull request #1171
Opened 2023-10-17 18:18 UTC by Yogesh01000100

Closes issue: #1134

## 📜 Summary of changes:

This pull request addresses the following changes related to header creation:

- [x] Implemented a dynamic way to add, edit, and remove headers.
- [x] Added error handling to display validation errors related to headers.
 
![image](https://github.com/requestly/requestly/assets/90953665/0c6db2a7-14d6-421e-bd9a-77243ba5e5f3)

## ✅ Checklist:

- [x] Make sure linting and unit tests pass.
- [x] No install/build warnings introduced.
- [x] Verified UI in browser.
- [ ] For UI changes, added/updated analytics events (if applicable).
- [ ] For changes in extension's code, manually tested in Chrome and Firefox.
- [ ] For changes in extension's code, both MV2 and MV3 are covered.
- [ ] Added/updated unit tests for this change.
- [ ] Raised pull request to update corresponding documentation (if already exists).

## 🧪 Test instructions:

To test these changes, follow these steps:

1. Browse to the app folder and run the application.
2. Navigate to the Mock server from the sidebar section.
3. See for any already created mocks.
4. If it exists then click on it and check the response headers option.
5. Add new headers, edit existing ones, and remove headers.
6. Ensure that validation errors are displayed.

2023-10-20 05:48 UTC, Yogesh01000100 commented
@rohanmathur91 @RuntimeTerror10 @wrongsahil can you help merging this pull request?

2023-10-20 11:30 UTC, wrongsahil commented
@Yogesh01000100 Please attach [Session Replay](https://requestly.io/products/session-replays) in the PR description

2023-10-21 11:38 UTC, Yogesh01000100 commented
> @Yogesh01000100 Please attach [Session Replay](https://requestly.io/products/session-replays) in the PR description

please check the session, in the pull request description, (updated)

2023-10-24 09:34 UTC, Yogesh01000100 commented
> > @Yogesh01000100 Please attach [Session Replay](https://requestly.io/products/session-replays) in the PR description
> 
> @wrongsahil @RuntimeTerror10 please check the session, in the pull request description, (updated)

@RuntimeTerror10 can please check with the pull request that I put, and do let me know if any changes are required.

2023-10-29 19:54 UTC, Yogesh01000100 commented
@RuntimeTerror10 @wrongsahil can you check and help merge this PR?

2023-10-30 10:46 UTC, RuntimeTerror10 commented
Hey @Yogesh01000100 , I will review it today and will share any changes if required by tomorrow.

2023-10-31 05:41 UTC, Yogesh01000100 commented
> Hey @Yogesh01000100 , I will review it today and will share any changes if required by tomorrow.

okay sure!

2023-11-11 09:21 UTC, Yogesh01000100 commented
> Hey @Yogesh01000100 , I will review it today and will share any changes if required by tomorrow.

Have you reviewed it? if any changes are there please inform me.

2023-11-13 10:30 UTC, RuntimeTerror10 requested changes

2023-11-13 10:30 UTC, RuntimeTerror10 commented on app/src/components/features/mocksV2/MockEditorIndex/Editor/HeaderSection/index.tsx
> +  };
We should not perform checks on strings to determine if the error is for header `name` or `value`, error messages might change in future which will break this.

2023-11-13 10:30 UTC, RuntimeTerror10 commented on app/src/components/features/mocksV2/MockEditorIndex/utils.ts
> +      error.typeOfError = "name Header name is required";
Set type of error to either `name` or `value`, and add other property to error object named `description` which will be rendered below respective inputs.

2023-11-13 10:30 UTC, RuntimeTerror10 commented on app/src/components/features/mocksV2/MockEditorIndex/utils.ts
> +      error.typeOfError = "name Header name is required";
Also remove the error type suffix added on each error message

2023-11-13 10:34 UTC, RuntimeTerror10 commented
@Yogesh01000100  Suggested UX change:
Instead of clicking on `Add modification` button to add a new header, can we automatically create a new empty header value-name pair when the user has added some value to the last header name-value field?

2023-11-13 10:40 UTC, RuntimeTerror10 commented
@Yogesh01000100 Added comments and one UX change

2023-12-17 20:32 UTC, Yogesh01000100 commented
> @Yogesh01000100 Added comments and one UX change

I've implemented the requested changes and added the new automatic header field creation upon user input.

2024-02-06 18:57 UTC, Yogesh01000100 commented
Hi @RuntimeTerror10 
It has been about two months since I submitted the pull request, and I haven't received any feedback or response. I understand that everyone is busy, and I appreciate your time and effort in reviewing pull requests.

I'm reaching out to inquire about the status of the review for this pull request. If there are specific concerns or changes needed, I'm more than willing to address them.

2024-02-07 17:19 UTC, RuntimeTerror10 commented
Hey @Yogesh01000100 
Sorry for the delay, I'll review your pull request and will get back to you soon with feedback.

2024-03-12 21:03 UTC, Yogesh01000100 commented
> Hey @Yogesh01000100 Sorry for the delay, I'll review your pull request and will get back to you soon with feedback.

 I understand that you're likely juggling a lot of responsibilities, and I appreciate the effort it takes to manage this project.

If there have been any developments regarding the review, or if there's any additional information or modifications you need from my end, please let me know. I'm eager to contribute and to make any necessary adjustments to my submission.

2024-07-08 05:49 UTC, wrongsahil commented
Closing this as of now as lot of things has changes in codebase.

2024-07-08 05:49 UTC, closed without merging