fix: await pending transactions before changing workspace details
requestly/requestly pull request #1415
Opened 2024-02-13 03:52 UTC by nsrCodes

Closes issue: 

## 📜 Summary of changes:

## ✅ Checklist:

- [ ] Make sure linting and unit tests pass.
- [ ] No install/build warnings introduced.
- [ ] Verified UI in browser.
- [ ] For UI changes, added/updated analytics events (if applicable).
- [ ] For changes in extension's code, manually tested in Chrome and Firefox.
- [ ] For changes in extension's code, both MV2 and MV3 are covered.
- [ ] Added/updated unit tests for this change.
- [ ] Raised pull request to update corresponding documentation (if already exists).

## 🧪 Test instructions:

## 🔗 Other references:

2024-02-13 09:30 UTC, sagarsoni7 commented
Thanks Navdeep, will complete review by tonight.

2024-02-14 00:17 UTC, sagarsoni7 requested changes

2024-02-14 00:46 UTC, sagarsoni7 commented on app/src/utils/StorageServiceWrapper.js
> +    this.transactionLedger = {};
https://github.com/requestly/requestly/pull/1420

2024-02-14 19:46 UTC, nsrCodes commented on app/src/utils/StorageServiceWrapper.js
> +    this.transactionLedger = {};
thanks for the improvements @sagarsoni7

2024-02-14 19:46 UTC, nsrCodes commented on app/src/utils/StorageServiceWrapper.js
> +    promise.then(() => {
also covered in https://github.com/requestly/requestly/pull/1420

2024-02-14 22:52 UTC, sagarsoni7 approved these changes

2024-02-14 22:53 UTC, merged