[ENGG-1405] : Automate user addition in billing team on approval
requestly/requestly pull request #1521
Opened 2024-03-22 08:40 UTC by RuntimeTerror10

Closes issue: 

## 📜 Summary of changes:

## ✅ Checklist:

- [ ] Make sure linting and unit tests pass.
- [ ] No install/build warnings introduced.
- [ ] Verified UI in browser.
- [ ] For UI changes, added/updated analytics events (if applicable).
- [ ] For changes in extension's code, manually tested in Chrome and Firefox.
- [ ] For changes in extension's code, both MV2 and MV3 are covered.
- [ ] Added/updated unit tests for this change.
- [ ] Raised pull request to update corresponding documentation (if already exists).

## 🧪 Test instructions:

## 🔗 Other references:

2024-03-26 05:19 UTC, wrongsahil requested changes

2024-03-26 05:23 UTC, wrongsahil requested changes

2024-03-26 05:23 UTC, wrongsahil commented on app/src/features/settings/components/BillingTeam/types.ts
> +}
No need to create enums for 1 time use string literals. Can create local method constants only

2024-03-26 05:23 UTC, wrongsahil commented on app/src/features/settings/components/BillingTeam/index.tsx
> +
Need to refractor this into a separate component

2024-03-26 14:47 UTC, nafees87n commented on app/src/features/settings/components/BillingTeam/components/BillingDetails/index.tsx
> +const BILLING_TEAM_JOIN_REQUEST_ACTION = {
```suggestion
enum BILLING_TEAM_JOIN_REQUEST_ACTION = {
```

2024-03-26 14:47 UTC, nafees87n commented on app/src/features/settings/components/BillingTeam/components/BillingDetails/index.tsx
> +  const isTeamMember = useBillingTeamFetcher(hasAccessToBillingTeam, billingId);
```suggestion
  const isPartOfCurrentTeam = useFetchBillingTeam(hasAccessToBillingTeam, billingId);
```

2024-03-26 14:49 UTC, nafees87n commented on app/src/features/settings/components/BillingTeam/components/BillingDetails/index.tsx
> +  const isTeamMember = useBillingTeamFetcher(hasAccessToBillingTeam, billingId);
Instead of separate checks, `useBillingTeamFetcher` can be modified for both the usecases. Please rename the hook appropriately

2024-03-26 15:30 UTC, RuntimeTerror10 commented on app/src/styles/custom/custom.scss
> +}
Yes, this will only change the bg color of toasts

2024-03-27 07:00 UTC, nafees87n approved these changes

2024-03-27 11:28 UTC, wrongsahil requested changes

2024-03-27 11:28 UTC, wrongsahil commented on app/src/features/settings/components/BillingTeam/index.tsx
> +  return <BillingList />;
I don't see sidebar getting rendered here?? Where is it rendering from?

2024-03-29 08:36 UTC, wrongsahil approved these changes

2024-03-29 08:36 UTC, wrongsahil commented on app/src/features/settings/components/BillingTeam/index.tsx
> +  const joiningRequestAction = queryParams.get("joinRequestAction");
`joiningRequestAction` -> `joinRequestAction`

2024-03-29 10:04 UTC, merged