feat: compress pair values of certain rule types
requestly/requestly pull request #1534
Opened 2024-03-29 08:51 UTC by nsrCodes

compresses the pair value for 
1. Response rule
2. Request rule
3. Script rule that are of code type

in transit (to and from firebase) and storage. 
Syncing still works on the complete (uncompressed) records

2024-03-30 10:29 UTC, sagarsoni7 commented
We’re first compressing the rule data and then encoding it to base64.
Wouldn’t encoding to base64 increase the size again?
If we are doing base64 encoding to convert it into text to set data in Realtime db, how about directly pushing the compressed outcome to Firestore DB instead? It accepts ByteString

For now, we can move forward with RealtimeDB but we still have the future scope to compress further by moving rules to FirestoreDB right? Of course Firestore has its own challenges we know

2024-03-30 10:42 UTC, sagarsoni7 approved these changes

2024-04-02 03:57 UTC, wrongsahil requested changes

2024-04-02 03:57 UTC, wrongsahil commented on app/src/utils/Compression.js
> +        console.log("This rule type should not need compression");
Remove log

2024-04-02 03:57 UTC, wrongsahil commented on app/src/utils/Compression.js
> +    if (shouldDecompressRecord(recordId)) {
This looks redundant as this check is already present in decompressRecords.

2024-04-02 03:57 UTC, wrongsahil commented on app/src/utils/Compression.js
> +  if (isRule(record)) {
Missing Check for `isCompressed` key

2024-04-02 04:51 UTC, nsrCodes commented on app/src/utils/Compression.js
> +  if (isRule(record)) {
this is handled below on the pair level

2024-04-02 06:05 UTC, wrongsahil approved these changes

2024-04-02 12:13 UTC, merged