[ENGG-1555] refactor: implement mock server table using ContentList component
requestly/requestly pull request #1602
Opened 2024-04-16 12:01 UTC by rohanmathur91

Closes issue: 

## 📜 Summary of changes:

## ✅ Checklist:

- [ ] Make sure linting and unit tests pass.
- [ ] No install/build warnings introduced.
- [ ] Verified UI in browser.
- [ ] For UI changes, added/updated analytics events (if applicable).
- [ ] For changes in extension's code, manually tested in Chrome and Firefox.
- [ ] For changes in extension's code, both MV2 and MV3 are covered.
- [ ] Added/updated unit tests for this change.
- [ ] Raised pull request to update corresponding documentation (if already exists).

## 🧪 Test instructions:

## 🔗 Other references:

2024-04-18 07:58 UTC, wrongsahil requested changes

2024-04-18 07:58 UTC, wrongsahil commented on app/src/features/mocks/container.scss
> +.mocks-container {
No need to define this css. This should get autodefined when you wrap SecondarySidebarLayout

2024-04-18 07:58 UTC, wrongsahil commented on app/src/features/mocks/routes.tsx
> +        index: true,
Index true is unnecessary here

2024-04-18 12:50 UTC, rohanmathur91 commented on app/src/features/mocks/types/index.ts
> +}
Removed analytics too

2024-04-19 07:12 UTC, wrongsahil approved these changes

2024-04-19 08:43 UTC, merged