Fetch payload dynamically in request/response details
requestly/requestly pull request #2084
Opened 2024-08-16 04:29 UTC by nsrCodes

builds on top of changes here - https://github.com/requestly/requestly-cloud/pull/399

2024-08-20 08:26 UTC, rohanmathur91 requested changes

2024-08-20 08:26 UTC, rohanmathur91 commented on app/src/lib/design-system/components/RQNetworkTable/GenericNetworkTable/components/NetworkPayload.tsx
> +  fetchPayload?: () => Promise<any>;
`fetchPayload` this should not be exposed from `NetworkPayload`, ideally `NetworkPayload` should just take the payload, it should not know how to fetch any payload.

2024-08-20 08:26 UTC, rohanmathur91 commented on app/src/lib/design-system/components/RQNetworkTable/GenericNetworkTable/components/NetworkPayload.tsx
> +        });
`RQNetworkTable` should know the currently selected log ie its parent component should know the selected log and there we should fetch the payload for the selected log and just update the logs state.

2024-08-20 08:26 UTC, rohanmathur91 commented on app/src/lib/design-system/components/RQNetworkTable/GenericNetworkTable/components/NetworkPayload.tsx
> +  if (typeof finalPayload === "object") {
Will `finalPayload` be ever `null`, if yes then we should add that check too.

2024-08-22 10:28 UTC, rohanmathur91 requested changes

2024-08-22 10:28 UTC, rohanmathur91 commented on app/src/lib/design-system/components/RQNetworkTable/index.tsx
> +    let finalLogs = logs;
Create a copy of logs, the above might be working now, but might cause some unexpected issues in future
```suggestion
    let finalLogs = [...logs];
```

2024-08-22 10:31 UTC, nsrCodes commented on app/src/lib/design-system/components/RQNetworkTable/index.tsx
> +  const [selectedLog, setSelectedLog] = useState<RQNetworkLog | null>(null);
no. `activeLogId` is the used for syncing with the time in session recording viewer

2024-08-22 10:37 UTC, rohanmathur91 approved these changes

2024-08-22 10:37 UTC, rohanmathur91 commented on app/src/lib/design-system/components/RQNetworkTable/index.tsx
> +  const [selectedLog, setSelectedLog] = useState<RQNetworkLog | null>(null);
So can we give a more descriptive name?

2024-08-22 11:37 UTC, merged