fix: Resource type not visible in Firefox Requestly Devtools
requestly/requestly pull request #2153
Opened 2024-09-08 21:15 UTC by adarsh-sgh

Fixes #1126 
After this code change whenever a network event comes we will set the `_resourceType` attribute of the event if it's not already set (which is in case of firefox).
Using similar logic that chromium uses to get `_resourceType`. See the `fromMimeType` function [here](https://chromium.googlesource.com/chromium/src.git/+/64.0.3261.1/third_party/WebKit/Source/devtools/front_end/common/ResourceType.js)

## Before the fix
![image](https://github.com/user-attachments/assets/69250b02-3a5c-4d01-979b-4e4586acbbe0)

## After the fix

<img width="1272" alt="image" src="https://github.com/user-attachments/assets/1ab349ae-376f-4627-a3f2-01584fb3b779">

2024-09-13 20:55 UTC, adarsh-sgh commented
@wrongsahil  @sagarsoni7 This PR implemets the solution as discussed in the issue #1126 
requesting your review on this.

2024-12-07 20:34 UTC, adarsh-sgh commented
@wrongsahil @sagarsoni7 can we please get this PR reviewed, this issue is open since more than 1 years.

2025-01-14 08:42 UTC, wrongsahil requested changes

2025-01-14 08:42 UTC, wrongsahil commented on browser-extension/common/src/devtools/utils.ts
> +  const mimeType = networkEvent.response.content.mimeType;
```suggestion
  const mimeType = networkEvent?.response?.content?.mimeType;
  if(!mimeType) return NetworkResourceType.OTHER;
```

2025-01-14 08:42 UTC, wrongsahil commented
@adarsh-sgh Just one small change. Rest looks good

2025-01-14 10:53 UTC, adarsh-sgh commented
> @adarsh-sgh Just one small change. Rest looks good

Done @wrongsahil

2025-01-15 03:32 UTC, wrongsahil approved these changes
This looks good now. LGTM.

Thanks for helping out @adarsh-sgh :D . We're planning to release MV3 version of Firefox this week. Will release this with that

2025-01-15 03:32 UTC, merged