[ENGG-2209]: replace rule buttons with design system button
requestly/requestly pull request #2197
Opened 2024-09-23 13:45 UTC by rohanmathur91

<img width="498" alt="Screenshot 2024-09-23 at 7 12 55 PM" src="https://github.com/user-attachments/assets/fcb1b87f-5493-4993-b12c-47a87af052a1">
<img width="904" alt="Screenshot 2024-09-23 at 7 14 23 PM" src="https://github.com/user-attachments/assets/cccf348e-030b-4486-824a-220a17e91bd0">

2024-09-24 09:47 UTC, RuntimeTerror10 approved these changes

2024-09-25 09:05 UTC, wrongsahil requested changes

2024-09-26 10:27 UTC, rohanmathur91 commented on app/src/features/rules/constants/index.ts
> +    displayText: "ESC",
This wont work for `CMD` since its hotkey is `meta` so had to keep this

2024-09-26 10:33 UTC, rohanmathur91 commented on app/src/views/features/rules/RuleEditor/components/Header/EditorGroupDropdown/index.tsx
> +              height={6}
> Seems redundant, can we keep one?

This values will be used before the image is loaded to reserve the space, [read more](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#height).

2024-09-26 10:47 UTC, rohanmathur91 commented on app/src/views/features/rules/RuleEditor/components/Header/ActionButtons/CloseButton/index.js
> +        icon={<FiArrowLeft />}
`md` icon was too big compare to this, so going with this

2024-09-26 18:45 UTC, wrongsahil commented on app/src/features/rules/constants/index.ts
> +    displayText: "ESC",
Can't we add logic rendering text by detecting it from the hotKey only?

2024-09-27 01:01 UTC, wrongsahil approved these changes

2024-09-30 08:27 UTC, rohanmathur91 commented on app/src/features/rules/constants/index.ts
> +    displayText: "ESC",
Yes, we can.

2024-09-30 08:27 UTC, merged