poc: auto completes for variables and scripts
requestly/requestly pull request #2442
Opened 2024-12-20 10:57 UTC by nsrCodes

todo: provide the write interface to this for the codeEditor consumers

2024-12-24 05:58 UTC, iostreamer-X requested changes
Hey @nsrCodes! Let's pause on this implementation for now.

Firstly, the code is good, but it's the fundamental behaviour that's of concern.
We didn't receive this requirement, rather we are the ones pushing for it, so there's no inherent rush to deliver.

Secondly, we are bringing ourselves at par with script editing experiences provided by other clients. And they have set the bar at full intellisense.
So we can't be delivering anything below that, as that might erode the trust on API client itself.

So, for now we will be pausing with this fuzzy search implementation and plan out for full intellisense.

2024-12-24 06:09 UTC, wrongsahil commented
> Hey @nsrCodes! Let's pause on this implementation for now.
> 
> Firstly, the code is good, but it's the fundamental behaviour that's of concern. We didn't receive this requirement, rather we are the ones pushing for it, so there's no inherent rush to deliver.
> 
> Secondly, we are bringing ourselves at par with script editing experiences provided by other clients. And they have set the bar at full intellisense. So we can't be delivering anything below that, as that might erode the trust on API client itself.
> 
> So, for now we will be pausing with this fuzzy search implementation and plan out for full intellisense.

We can keep the variables autocomplete though as it doesn't depend on intellisense

2025-01-13 06:11 UTC, nafees87n approved these changes

2025-01-13 06:16 UTC, iostreamer-X approved these changes

2025-01-13 06:17 UTC, merged