ENG-2723-> Collapse collections by default
requestly/requestly pull request #2485
Opened 2024-12-31 11:03 UTC by Ethical98

2025-01-09 10:32 UTC, rohanmathur91 requested changes

2025-01-09 10:32 UTC, rohanmathur91 commented on app/src/features/apiClient/screens/apiClient/components/sidebar/components/collectionsList/CollectionsList.tsx
> +  const [activeKeys, setActiveKeys] = useState(sessionStorage.getItem("active_collection_keys", []));
```suggestion

const SESSION_STORAGE_ACTIVE_COLLECTIONS_KEY = "active_collection_keys" // keep it in constants.ts
  const [activeKeys, setActiveKeys] = useState(sessionStorage.getItem("active_collection_keys", []));
```

2025-01-09 10:32 UTC, rohanmathur91 commented on app/src/features/apiClient/screens/apiClient/utils.ts
> +
Can we avoid this DFS and have a simpler logic for this?

2025-01-09 10:32 UTC, rohanmathur91 commented on app/src/features/apiClient/screens/apiClient/components/sidebar/components/collectionsList/CollectionsList.tsx
> +  const [activeKeys, setActiveKeys] = useState(sessionStorage.getItem("active_collection_keys", []));
Also update all its instances

2025-01-09 10:32 UTC, rohanmathur91 commented on app/src/features/apiClient/screens/apiClient/components/sidebar/components/collectionsList/collectionRow/CollectionRow.tsx
> +    sessionStorage.removeItem("collapsed_collection_keys");
Cant we use the same key?

2025-01-10 09:54 UTC, Ethical98 commented on app/src/features/apiClient/screens/apiClient/components/sidebar/components/collectionsList/collectionRow/CollectionRow.tsx
> +    sessionStorage.removeItem("collapsed_collection_keys");
Earlier we used to expand all collections but now the case is opposite so to maintain the collapsed keys state will be very expensive and if we keep the active keys in collapsed it would be misleading. So it think its better to remove it and continue with `active_collection_keys`

2025-01-10 11:00 UTC, rohanmathur91 requested changes

2025-01-10 11:00 UTC, rohanmathur91 commented on app/src/features/apiClient/screens/apiClient/components/sidebar/components/collectionsList/CollectionsList.tsx
> +  const [activeKeys, setActiveKeys] = useState(sessionStorage.getItem(SESSION_STORAGE_ACTIVE_COLLECTIONS_KEY, []));
```suggestion
  const [expandedCollectionIds, setExpandedCollectionIds] = useState(sessionStorage.getItem(SESSION_STORAGE_EXPANDED_COLLECTION_IDS, []));
```

2025-01-10 11:00 UTC, rohanmathur91 commented on app/src/features/apiClient/constants.ts
> +export const SESSION_STORAGE_ACTIVE_COLLECTIONS_KEY = "active_collection_keys";
```suggestion
export const SESSION_STORAGE_EXPANDED_COLLECTION_IDS_KEY = "expanded_collection_ids";
```

2025-01-10 11:00 UTC, rohanmathur91 commented on app/src/features/apiClient/contexts/apiClient.tsx
> +      clearActiveKeysFromSession(recordIdsToBeDeleted);
```suggestion
      clearExpandedCollectionIdsFromSession(recordIdsToBeDeleted);
```

2025-01-10 11:00 UTC, rohanmathur91 commented on app/src/features/apiClient/screens/apiClient/components/sidebar/components/collectionsList/CollectionsList.tsx
> +
```suggestion
const collectionsToBeExpanded = useMemo(() => {
const id = requestId || collectionId;

    if (!id){
      return
    }

return getCollectionIdsToBeExpanded(id, activeKeys, apiClientRecords,)
},[collectionId, requestId, activeKeys, apiClientRecords])

  useEffect(() => {
    setExpandedCollectionIds(collectionsToBeExpanded);
  }, [collectionsToBeExpanded]);

```

2025-01-10 11:00 UTC, rohanmathur91 commented on app/src/features/apiClient/screens/apiClient/components/sidebar/components/collectionsList/CollectionsList.tsx
> +                    updateActiveKeys={setActiveKeys}
```suggestion
                    expandedCollectionIds ={expandedCollectionIds}
                    updateExpandedCollectionIds ={setExpandedCollectionIds}
```

2025-01-10 11:00 UTC, rohanmathur91 commented on app/src/features/apiClient/screens/apiClient/components/sidebar/components/collectionsList/collectionRow/CollectionRow.tsx
> +      if (isEmpty(keys)) {
Can simply check for `keys.length`

2025-01-10 11:00 UTC, rohanmathur91 commented on app/src/features/apiClient/screens/apiClient/components/sidebar/components/collectionsList/collectionRow/CollectionRow.tsx
> +      if (isEmpty(keys)) {
When will this case happen?

2025-01-10 11:00 UTC, rohanmathur91 commented on app/src/features/apiClient/screens/apiClient/components/sidebar/components/collectionsList/collectionRow/CollectionRow.tsx
> +      isEmpty(activeKeysCopy)
```suggestion
      activeKeysCopy.lenth === 0
```

2025-01-10 11:00 UTC, rohanmathur91 commented on app/src/features/apiClient/screens/apiClient/components/sidebar/components/collectionsList/collectionRow/CollectionRow.tsx
> +        : sessionStorage.setItem(SESSION_STORAGE_ACTIVE_COLLECTIONS_KEY, activeKeysCopy);
Update the session storage keys as mention above

2025-01-10 11:00 UTC, rohanmathur91 commented on app/src/features/apiClient/screens/apiClient/components/sidebar/components/collectionsList/collectionRow/CollectionRow.tsx
> +  }, [activeKeys, record.id]);
No need of state and useEffect
```suggestion
 const activeKey = activeKeys?.includes(record.id) ? record.id : null
```

2025-01-10 11:00 UTC, rohanmathur91 commented on app/src/features/apiClient/screens/apiClient/components/sidebar/components/collectionsList/collectionRow/CollectionRow.tsx
> +       which was added due to the previous logic can be removed after some time */
Add a `TODO` comment here for the same

2025-01-10 11:00 UTC, rohanmathur91 commented on app/src/features/apiClient/screens/apiClient/utils.ts
> +export const clearActiveKeysFromSession = (keysToBeDeleted: string[]) => {
```suggestion
export const clearExpandedCollectionIdsFromSession = (idsToBeDeleted: string[]) => {
```

2025-01-10 11:00 UTC, rohanmathur91 commented on app/src/features/apiClient/screens/apiClient/utils.ts
> +};
```suggestion
 if (keysToBeDeleted.length === 0) {
    return;
  }
 
  const activeKeys = sessionStorage.getItem(SESSION_STORAGE_ACTIVE_COLLECTIONS_KEY, []);
  
  const updatedActiveKeys: string[] = [];

  activeKeys.forEach((key: string) => {
    if (!keysToBeDeleted.includes(key)) updatedActiveKeys.push(key);
  });

  sessionStorage.setItem(SESSION_STORAGE_ACTIVE_COLLECTIONS_KEY, updatedActiveKeys);
};
```

2025-01-10 11:00 UTC, rohanmathur91 commented on app/src/features/apiClient/screens/apiClient/utils.ts
> +};
Have a util to get the expandedCollectionIds from session storage and reuse that, similarly for updation have a util.

```suggestion
export const getExpandedCollectionIdsFromSessionStorage = () => {
return sessionStorage.getItem(SESSION_STORAGE_ACTIVE_COLLECTIONS_KEY, []);
}
```

2025-01-10 11:00 UTC, rohanmathur91 commented on app/src/features/apiClient/screens/apiClient/utils.ts
> +export const updateActiveKeys = (records: RQAPI.Record[], id: RQAPI.Record["id"], activeKeys: RQAPI.Record["id"][]) => {
Reorder the params and update the function name
```suggestion
export const updateActiveKeys = (id: RQAPI.Record["id"], activeKeys: RQAPI.Record["id"][], records: RQAPI.Record[]) => {
```

2025-01-10 11:00 UTC, rohanmathur91 commented on app/src/features/apiClient/screens/apiClient/utils.ts
> + */
Remove the comment

2025-01-10 11:00 UTC, rohanmathur91 commented on app/src/features/apiClient/screens/apiClient/utils.ts
> +  };
Keep this function outside the `updateActiveKeys` function

2025-01-10 11:00 UTC, rohanmathur91 commented on app/src/features/apiClient/screens/apiClient/utils.ts
> +      currentId = idToCollectionMap[currentId];
```suggestion
    let currentId = targetId
    while (currentId) {
      currentId = idToCollectionMap[currentId];
      
      if (currentId){
      parentIds.push(currentId);
      }else{
      return
      }
```

2025-01-10 11:00 UTC, rohanmathur91 commented on app/src/features/apiClient/screens/apiClient/utils.ts
> +  });
```suggestion
  parentIds.forEach((id) => {
    if (!activeKeysCopy.includes(id)) {
      activeKeysCopy.push(id);
    }
  });
```

2025-01-10 11:00 UTC, rohanmathur91 requested changes
Lets rename the language from `active` to `expand` overall.

2025-01-13 14:44 UTC, Ethical98 commented on app/src/features/apiClient/screens/apiClient/utils.ts
> +      currentId = idToCollectionMap[currentId];
i dont think this refactor is required we are already checking for current in while loop then again checking it using if statement is redundant.

2025-01-13 14:45 UTC, Ethical98 commented on app/src/features/apiClient/screens/apiClient/components/sidebar/components/collectionsList/CollectionsList.tsx
> +
Any specific reason for this change? Any edge case that i am missing out ?

2025-01-14 04:46 UTC, Ethical98 commented on app/src/features/apiClient/screens/apiClient/components/sidebar/components/collectionsList/CollectionsList.tsx
> +
This approach is not covering all edge cases. User is not able to collapse the collection (opened in tab) in sidebar because as soon as it gets clicked then this useMemo runs and again adds the same collectionId in expandedIds. We need to run this only when URL changes and api client record changes that's why useEffect is not having a dependency of expandedIds and it is driven thru previousValue approach.

2025-01-14 09:41 UTC, merged