RQLY-1257: Add mocks to team workspace
requestly/requestly pull request #382
Opened 2023-03-11 05:47 UTC by nsrCodes

This adds support for shared mocks inside team workspace.
can also serve as an example for adding/updating custom claims in auth token

2023-03-11 09:28 UTC, wrongsahil commented
requestly/requestly-cloud#1

2023-03-13 13:01 UTC, wrongsahil requested changes

2023-03-15 13:15 UTC, wrongsahil commented on app/src/components/features/mocksV2/utils/index.ts
>        finalUrl = `https://${username}.requestly.dev/${endpoint}`;
if(username && !teamId)
      finalUrl = `https://${username}.requestly.dev/${endpoint}`;
      return finalUrl

2023-03-16 05:03 UTC, merged

2024-02-14 18:28 UTC, sagarsoni7 reviewed
lgtm