RQ-32: UI revamp of modify response rule
requestly/requestly pull request #395
Opened 2023-03-15 05:47 UTC by rohanmathur91

Closes issue: 

## 📜 Summary of changes:
<img width="1440" alt="Screenshot 2023-03-15 at 11 16 19 AM" src="https://user-images.githubusercontent.com/61556757/225218365-5ff5fea6-3884-465c-b4aa-cce80a255617.png">

## ✅ Checklist:

- [ ] Make sure linting and unit tests pass.
- [ ] No install/build warnings introduced.
- [ ] Verified UI in browser.
- [ ] For UI changes, added/updated analytics events (if applicable).
- [ ] For changes in extension's code, manually tested in Chrome and Firefox.
- [ ] For changes in extension's code, both MV2 and MV3 are covered.
- [ ] Added/updated unit tests for this change.
- [ ] Raised pull request to update corresponding documentation (if already exists).

## 🧪 Test instructions:

## 🔗 Other references:

2023-03-16 10:11 UTC, lazyvab requested changes

2023-03-16 10:14 UTC, lazyvab commented on app/src/components/features/rules/RulePairs/ResponseRuleResourceTypes/index.tsx
> +  const handleResourceTypeChange = (type: ResponseRuleResourceType) => {
If not done, please add analytics events on updating resource type and entering graphql operation name.

2023-03-16 12:56 UTC, lazyvab commented on app/src/components/features/rules/RulePairs/Filters/index.js
> +        new Date("Thu Mar 16 2023 11:49:04 GMT+0530") // date of new Modify response rule UI release
For existing rules, we should select `resourceType` as REST by default. 
So, a REST API rule with request payload filter is a legacy rule.

2023-03-16 12:58 UTC, rohanmathur91 commented on app/src/components/features/rules/RulePairs/Filters/index.js
> +        new Date("Thu Mar 16 2023 11:49:04 GMT+0530") // date of new Modify response rule UI release
Okay.

2023-03-17 16:17 UTC, lazyvab approved these changes

2023-03-18 09:24 UTC, merged