chore: show connect app modal on start if user has never connected any traffic source
requestly/requestly pull request #707
Opened 2023-06-10 02:47 UTC by nsrCodes

Adds a persistent `hasConnectedApp` key to the global slice.

The modal is shown once the proxy has started.

2023-06-10 02:51 UTC, nsrCodes commented
If we don't add the `isProxyRunning` check (which is what delays the opening of the modal, the user will be shown an empty modal like this 


https://github.com/requestly/requestly/assets/57226514/08bf3764-4474-4ed7-b8a1-3cb164a3b7d3

2023-06-14 05:12 UTC, wrongsahil requested changes

2023-06-14 05:12 UTC, wrongsahil commented on app/src/store/index.js
> +  "hasConnectedApp",
Why do we need to create another top level key here?  This can be added to `misc.persist`

2023-06-14 09:40 UTC, wrongsahil approved these changes

2023-06-14 10:14 UTC, merged