RQ-553: New onboarding scree for Session Recording home page
requestly/requestly pull request #793
Opened 2023-06-30 06:57 UTC by nsrCodes

These changes are usable but require the following changes before being merged:

- [ ] Exact compatible version of extension
- [ ] Route of settings page
- [ ] Main GIF (current changes include a dead youtube embed) 

<img width="1512" alt="Screenshot 2023-06-30 at 12 20 50 PM" src="https://github.com/requestly/requestly/assets/57226514/dccdcc36-c8bb-4932-b8c0-c3bdf927b03f">

2023-07-06 01:30 UTC, nsrCodes commented
updated UI. Can be merged now. Extension version can be added later, once released.
<img width="1512" alt="Screenshot 2023-07-06 at 6 58 33 AM" src="https://github.com/requestly/requestly/assets/57226514/0f8e2d88-1497-4fba-9e35-26692375b624">

2023-07-07 03:58 UTC, nsrCodes commented
Final UI 

https://github.com/requestly/requestly/assets/57226514/14eb6c28-b9fe-4e17-8b8a-e9cfd4dc0869

2023-07-07 06:27 UTC, nafees87n requested changes

2023-07-07 06:27 UTC, nafees87n commented on app/src/views/features/sessions/SessionsIndexPageContainer/SessionsIndexPage/OnboardingView.tsx
> +      />
We have this modal in redux. We can just toggle this using `dispatch(actions.toggleActiveModal({ modalName: "extensionModal",...props}));`

2023-07-07 06:27 UTC, nafees87n commented on app/src/views/features/sessions/SessionsIndexPageContainer/SessionsIndexPage/index.scss
> +      margin-bottom: 1rem;
Try to use `px` instead of relative units for margin, padding...

2023-07-07 08:43 UTC, nafees87n approved these changes

2023-07-07 08:52 UTC, merged