RQ-583 Stitch sessions on page navigation or refresh
requestly/requestly pull request #874
Opened 2023-07-24 11:37 UTC by lazyvab

## 📜 Summary of changes:

- Cache the previous session in the tab data in background when the client page is unloading.
- Unified the flow of session recording start/stop.
    - Only the background will send events to the client to start or stop the recording.
    - The background will send session config, flag whether it's a manual start and the previous session data.
-  The background will clear the cached previous session data in tab data in 2 cases:
    - The new page loaded in client was not referred from previous page where recording was ON.
    - The cached copy has been sent back to the new page loaded in client.

## ✅ Checklist:

- [ ] Make sure linting and unit tests pass.
- [ ] No install/build warnings introduced.
- [ ] Verified UI in browser.
- [ ] For UI changes, added/updated analytics events (if applicable).
- [ ] For changes in extension's code, manually tested in Chrome and Firefox.
- [ ] For changes in extension's code, both MV2 and MV3 are covered.
- [ ] Added/updated unit tests for this change.
- [ ] Raised pull request to update corresponding documentation (if already exists).

## 🧪 Test instructions:

2023-07-26 15:14 UTC, lazyvab commented on browser-extension/mv2/src/background/background.js
> +  if (frameId !== 0) {
All the iframes will trigger `onContentScriptLoadedNotification` event, but we should not trigger `START_RECORDING` event and execute other logic in this function more than once for a page. This iframe check will help to execute it once.

2023-07-26 15:19 UTC, lazyvab commented on browser-extension/mv2/src/background/background.js
> +      previousSession: null,
Right, I will fix it.

2023-07-27 06:35 UTC, nafees87n requested changes

2023-07-27 06:35 UTC, nafees87n commented on browser-extension/mv2/src/background/background.js
> +    window.tabService.setData(tab.id, BG.TAB_SERVICE_DATA.SESSION_RECORDING, { notifyOnStart: true });
```suggestion
    window.tabService.setData(tab.id, BG.TAB_SERVICE_DATA.SESSION_RECORDING, { notify: true });
```
We read `notify` in `RQ.SessionRecorder.startRecording`

2023-07-27 06:40 UTC, nafees87n approved these changes

2023-07-27 06:42 UTC, merged