feat: password less email sign in with magic link
requestly/requestly pull request #893
Opened 2023-08-03 20:04 UTC by nsrCodes

2023-08-04 06:54 UTC, nafees87n requested changes

2023-08-04 06:54 UTC, nafees87n commented on app/src/components/misc/SignInViaEmailLink/SignInViaEmailLink.js
> +            {userEmail && isProcessing ? <FaSpinner className="icon-spin mr-2" /> : "Login"}
We can use the loading prop in `RQButton`

2023-08-04 06:54 UTC, nafees87n commented on app/src/components/misc/SignInViaEmailLink/index.css
> +}
- These class names are generic. If you require class for a specific component, please use specific class names for the component.

- `mb-20` can be setup in `base.css` if you require.
- Avoid use of `!important`

2023-08-04 06:54 UTC, nafees87n commented on app/src/components/authentication/AuthForm/GenerateLoginLinkButton.jsx
> +      style={{
Shouldn't use inline style

2023-08-04 06:54 UTC, nafees87n commented on app/src/components/authentication/AuthForm/GenerateLoginLinkButton.jsx
> +      console.log(sendEmailLinkForSignin);
missed an debug log

2023-08-04 17:47 UTC, nafees87n approved these changes
@nsrCodes There is lint warning about unused components in `src/components/authentication/AuthForm/index.js`. Please fix that before merging.

2023-08-04 17:47 UTC, nafees87n commented on app/src/components/misc/SignInViaEmailLink/SignInViaEmailLink.js
> +            LOGIN
```suggestion
            Login
```

2023-09-15 04:27 UTC, nsrCodes commented
updated UI:
<img width="1166" alt="Screenshot 2023-09-15 at 9 55 08 AM" src="https://github.com/requestly/requestly/assets/57226514/08050f8c-bbb1-46b9-baf4-fcdf13613d91">
<img width="1512" alt="Screenshot 2023-09-15 at 9 55 19 AM" src="https://github.com/requestly/requestly/assets/57226514/8bcd74f4-7064-4982-8ad3-b1ee069553ce">
<img width="541" alt="Screenshot 2023-09-15 at 9 55 28 AM" src="https://github.com/requestly/requestly/assets/57226514/7702ad47-75bd-4875-8729-da1b05daadbb">

2023-09-15 09:46 UTC, RuntimeTerror10 commented
Magic link sign in button not visible in workspace onboarding login screen

<img width="545" alt="Screenshot 2023-09-15 at 3 14 54 PM" src="https://github.com/requestly/requestly/assets/53986600/90b92cc9-7d60-4fd3-a4b3-1117099c0844">

2023-09-19 09:38 UTC, RuntimeTerror10 approved these changes

2023-09-22 04:22 UTC, nsrCodes commented
updated auth modals
<img width="518" alt="Screenshot 2023-09-22 at 9 48 21 AM" src="https://github.com/requestly/requestly/assets/57226514/070b6b3b-6481-4e34-bdb7-4cbd2e480047">
<img width="1212" alt="Screenshot 2023-09-22 at 9 48 34 AM" src="https://github.com/requestly/requestly/assets/57226514/899c7193-eb42-49da-b076-3c9b66b26633">

2023-09-22 04:49 UTC, merged