Added Pricing Page For Session Recording
requestly/requestly pull request #940
Opened 2023-08-11 14:38 UTC by Kanishkrawatt

Closes issue: 

## 📜 Summary of changes:

## ✅ Checklist:

- [ ] Updated Http-rules Pricing
- [ ] Create Pricing for Session Replay
 
## 🧪 Test instructions:

## 🔗 Other references:

2023-08-12 07:21 UTC, RuntimeTerror10 requested changes

2023-08-13 07:52 UTC, RuntimeTerror10 approved these changes

2023-08-14 06:30 UTC, sagarsoni7 requested changes

2023-08-14 06:47 UTC, sagarsoni7 approved these changes

2023-08-14 07:01 UTC, sagarsoni7 requested changes
Please resolve issues as discussed.

2023-08-14 07:26 UTC, sagarsoni7 approved these changes

2023-08-14 07:26 UTC, merged