RQ-774: cleanup PH launch changes
requestly/requestly pull request #977
Opened 2023-08-21 10:11 UTC by RuntimeTerror10

Closes issue: 

## 📜 Summary of changes:

- Revert back header to slack community and star
- Comment out app header
- Remove logic for showing auth modal explicitly and setting user attribute if ref is producthunt
- revert activate deal logic

## ✅ Checklist:

- [ ] Make sure linting and unit tests pass.
- [ ] No install/build warnings introduced.
- [ ] Verified UI in browser.
- [ ] For UI changes, added/updated analytics events (if applicable).
- [ ] For changes in extension's code, manually tested in Chrome and Firefox.
- [ ] For changes in extension's code, both MV2 and MV3 are covered.
- [ ] Added/updated unit tests for this change.
- [ ] Raised pull request to update corresponding documentation (if already exists).

## 🧪 Test instructions:

## 🔗 Other references:

2023-08-21 13:17 UTC, wrongsahil requested changes

2023-08-21 13:17 UTC, wrongsahil commented on app/src/components/user/AccountIndexPage/ManageAccount/ActiveLicenseInfo/index.js
>        {doesSubscriptionExist ? renderSubscriptionInfo() : renderGetASubscription()}
@RuntimeTerror10 Don't remove this. We still need to show the plan user got during PH launch

2023-08-21 14:21 UTC, rohanmathur91 approved these changes
LGTM!

2023-08-22 03:35 UTC, wrongsahil approved these changes

2023-08-22 03:50 UTC, merged